In [2]:
import numpy as np
arr=np.array([12,13,14,15,16])
arr

array([12, 13, 14, 15, 16])

In [3]:
print(arr)

[12 13 14 15 16]


In [4]:
arr.dtype

dtype('int64')

In [8]:
a=np.array([
    [1,2,3],
    [4,5,6]
])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
a.shape


(2, 3)

In [11]:
a.ndim

2

In [12]:
a.size

6

In [13]:
a[1]

array([4, 5, 6])

In [16]:
a[1][2]

np.int64(6)

In [17]:
int(a[1][2])

6

In [18]:
a[1,0]

np.int64(4)

In [19]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a[1]=99

In [21]:
a

array([[ 1,  2,  3],
       [99, 99, 99]])