# 

In [1]:
import numpy as np
a=np.arange(4)

In [3]:
a[0]

np.int64(0)

In [4]:
int(a[1])

1

In [5]:
a

array([0, 1, 2, 3])

In [7]:
a[[True,False,False,True]]

array([0, 3])

In [8]:
a>=2


array([False, False,  True,  True])

In [9]:
a[a>=2]

array([2, 3])

In [10]:
a[a>a.mean()]

array([2, 3])

In [11]:
b=np.arange(12)
b.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
A=np.random.randint(100,size=(3,3))

In [15]:
A


array([[64,  7, 46],
       [29, 31, 35],
       [93, 53, 94]], dtype=int32)

In [16]:
A>30

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])