In [3]:
import numpy as np
import pandas as pd

In [4]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [5]:
a.sum()

np.float64(nan)

In [8]:
np.mean(a)

np.float64(nan)

In [10]:
3+ None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [11]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [13]:
np.inf #infinite loop

inf

In [14]:
np.inf/np.inf

nan

In [15]:
3/np.inf

0.0

In [16]:
np.inf/3

inf

In [18]:
b = np.array([1, 2, 3, np.inf, np.nan, 4])

In [19]:
b.sum()

np.float64(nan)

In [22]:
np.isinf(np.inf)

np.True_

In [25]:
np.isnan(np.nan)

np.True_

In [26]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [29]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [30]:
a[np.isfinite(a)]     #Same output because it return a boolean array (false for np.nan or np.inf)

array([1., 2., 3., 4.])

In [31]:
pd.isnull(a)

array([False, False, False,  True,  True, False])

In [32]:
pd.isna(np.nan)

True

In [33]:
pd.notnull(pd.Series([1, np.nan, 7]))

0     True
1    False
2     True
dtype: bool

In [34]:
pd.isnull(pd.DataFrame({
    'Column A': [1, np.nan, 7],
    'Column B': [np.nan, 2, 3],
    'Column C': [np.nan, 2, np.nan]
}))

Column A  Column B  Column C
0     False      True      True
1      True     False     False
2     False     False      True

In [35]:
pd.notnull(pd.DataFrame({
    'Column A': [1, np.nan, 7],
    'Column B': [np.nan, 2, 3],
    'Column C': [np.nan, 2, np.nan]
}))

Column A  Column B  Column C
0      True     False     False
1     False      True      True
2      True      True     False

In [36]:
pd.Series([1, 2, np.nan]).count()

np.int64(2)

In [38]:
pd.Series([1, 2, np.nan]).sum()  #in pdandas series sum and count function igoner null values

np.float64(3.0)

In [39]:
s = pd.Series([1, 2, 3, np.nan, np.nan, 4])

In [40]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [41]:
s.dropna()

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [44]:
s.dropna()

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [53]:
s


0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [49]:
s.reset_index()

index    0
0      0  1.0
1      1  2.0
2      2  3.0
3      5  4.0

In [52]:
pd.notnull(s).sum()

np.int64(4)

In [54]:
df = pd.DataFrame({
    'Column A': [1, np.nan, 30, np.nan],
    'Column B': [2, 8, 31, np.nan],
    'Column C': [np.nan, 9, 32, 100],
    'Column D': [5, 8, 34, 110],
})

In [57]:
df.dropna()

Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [58]:
df

Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [61]:
df.dropna(axis=0)

Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [62]:
df.dropna(axis=1)

Column D
0         5
1         8
2        34
3       110