In [2]:
import numpy as np

In [4]:
a=np.arange(4)

In [5]:
a

array([0, 1, 2, 3])

In [6]:
a+=10

In [7]:
a

array([10, 11, 12, 13])

In [8]:
a*10

array([100, 110, 120, 130])

In [9]:
a

array([10, 11, 12, 13])

In [10]:
[i *10 for i in a]

[np.int64(100), np.int64(110), np.int64(120), np.int64(130)]

In [11]:
print(a)

[10 11 12 13]


In [12]:
b=np.array([0,1,2,3])
b

array([0, 1, 2, 3])

In [13]:
a+b

array([10, 12, 14, 16])

In [14]:
a*b

array([ 0, 11, 24, 39])